
# Makefile for Writing Make Files Example

# *****************************************************
# Variables to control Makefile operation

CC = gcc
CCFLAGS = -Wall
FILES = *.c

# ****************************************************
# Targets needed to bring the executable up to date
build: $(FILES)
	$(CC) -o output $(FILES)
# main: main.o
# (CXX) (CXXFLAGS) -o main main.o

# # The main.o target can be written more simply

# main.o: main.c
# 	$(CXX) $(CXXFLAGS) -c main.c
