clk = 0
CLK_PHASE = 5
computeCycle = 10
computeEnd = ->@565 ps
computeStart = ->@555 ps
correctResult = 0
dut_busy = 1
dut_run = 0
dut_sram_read_address = 10
dut_sram_write_address = x
dut_sram_write_data = x
dut_sram_write_enable = 0
dut_wmem_read_address = 5
endTime = 565
golden_result_array =  
i = 0
j = 1
k = 1
NUM_RESULT = 96
p = 0
q = 0
reset_b = -1
RESULT_ADDR = 95
result_array =  
ROUND = 1
sram_dut_read_data = 16
startTime = 555
wmem_dut_read_data = 21825
